name: mi_card
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  google_fonts: ^1.0.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true


  assets:
    - Images/myPhoto.png
  fonts:
    - family: Parisienne
      fonts:
      - asset: google_fonts/Parisienne-Regular.ttf

    - family: Almendra
      fonts:
      - asset: google_fonts/AlmendraDisplay-Regular.ttf
